development:
  adapter: postgresql
  database: spatialaccess_development
  pool: 5
  timeout: 5000
  username: postgres
  password: p20o20e13
  host: localhost
#  template: template0
test:
  adapter: postgresql
  database: spatialaccess_test
  pool: 5
  timeout: 5000
  username: postgres
  password: p20o20e13
  host: localhost
#  template: template0

production:
  adapter: postgresql
  database: spatialaccess_production
  pool: 5
  timeout: 5000
  username: postgres
  password: 19loki76